# Generated by Django 2.1.5 on 2019-01-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
