# Generated by Django 2.1.5 on 2019-01-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20190127_0014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
